site_name: mobile_coverage
site_description: Get your home mobile network coverage
repo_url: https://github.com/guminski/mobile_coverage
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/guminski">guminski</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
