# Generated by Django 2.1.9 on 2020-02-19 19:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_2G', models.BooleanField(default=False)),
                ('coverage_3G', models.BooleanField(default=False)),
                ('coverage_4G', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, blank=True, null=True, verbose_name="Operator's name")),
                ('network_code', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Network operator',
                'verbose_name_plural': 'Network operators',
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='search_api.NetworkOperator'),
        ),
    ]
