# Generated by Django 2.1.9 on 2020-02-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkoperator',
            name='network_code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
