# Generated by Django 2.1.9 on 2020-02-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_api', '0002_auto_20200219_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
    ]
